// haut 1
plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ludexa.moteur'
    compileSdk 34

    defaultConfig {
        applicationId "com.ludexa.moteur"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'net.lingala.zip4j:zip4j:2.11.5'
    implementation 'com.android.tools.build:apksig:8.5.0'
}
// bas 1
