name: Build Yop2D

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7

      - name: 1. Compiler la coquille vide (Runner)
        run: gradle assembleRunnerDebug

      - name: 2. Préparer le dossier assets de l'éditeur
        run: mkdir -p app/src/main/assets

      - name: 3. Injecter le Runner dans l'Éditeur
        run: cp app/build/outputs/apk/runner/debug/app-runner-debug.apk app/src/main/assets/modele_runner.apk

      - name: 4. Compiler l'Éditeur Yop2D
        run: gradle assembleEditeurDebug

      - name: Publier l'APK final (Yop2D + Runner inclus)
        uses: actions/upload-artifact@v4
        with:
          name: YOP2D-Editeur-apk
          path: app/build/outputs/apk/editeur/debug/app-editeur-debug.apk
          
